-- LICENSEURI https://yuruna.link/license
-- Copyright (c) 2026 by Alisson Sol et al.
-- AmisAd POC - seed skeleton for s003.silence: Consent Revocation and the Right to Silence
-- Loaded by test fixtures once the scenario is implemented; empty by design.
-- TODO(s003.silence): seed data for the real steps - see plan/scenarios.md (s003.silence).
