-- LICENSEURI https://yuruna.link/license
-- Copyright (c) 2026 by Alisson Sol et al.
-- AmisAd POC - seed skeleton for s007.inventory: Enterprise Integration Onboarding and Inventory-Truth Matching
-- Loaded by test fixtures once the scenario is implemented; empty by design.
-- TODO(s007.inventory): seed data for the real steps - see plan/scenarios.md (s007.inventory).
