-- LICENSEURI https://yuruna.link/license
-- Copyright (c) 2026 by Alisson Sol et al.
-- AmisAd POC - seed skeleton for s008.mediation: Zero-Knowledge Dispute Mediation and Settlement Adjustment
-- Loaded by test fixtures once the scenario is implemented; empty by design.
-- TODO(s008.mediation): seed data for the real steps - see plan/scenarios.md (s008.mediation).
