-- LICENSEURI https://yuruna.link/license
-- Copyright (c) 2026 by Alisson Sol et al.
-- AmisAd POC - seed skeleton for s009.suppression: Aggregate Insight Publication and the Demand-Planning Loop
-- Loaded by test fixtures once the scenario is implemented; empty by design.
-- TODO(s009.suppression): seed data for the real steps - see plan/scenarios.md (s009.suppression).
