-- LICENSEURI https://yuruna.link/license
-- Copyright (c) 2026 by Alisson Sol et al.
-- AmisAd POC - seed skeleton for SCENARIO-008: Zero-Knowledge Dispute Mediation and Settlement Adjustment
-- Loaded by test fixtures once the scenario is implemented; empty by design.
-- TODO(SCENARIO-008): seed data for the real steps - see plan/scenarios.md (SCENARIO-008).
