-- AmisAd POC - seed skeleton for SCENARIO-002: Considered Purchase, Constraint Fidelity, and In-Person Booking
-- Loaded by test fixtures once the scenario is implemented; empty by design.
-- TODO(SCENARIO-002):
--   - Need with exclusions (not dusty blue) and fitting deadline, manual closing
--   - Shortlist contains only fully fitting offers
--   - No commitment exists before the explicit decision
--   - One-tap booking; seller sees requirements, never identity
--   - Fulfill and settle; exactly two notifications delivered
--   - Assert: excluded offers absent, notification count equals two