-- LICENSEURI https://yuruna.link/license
-- Copyright (c) 2026 alius-git
-- AmisAd POC - seed skeleton for SCENARIO-003: Consent Revocation and the Right to Silence
-- Loaded by test fixtures once the scenario is implemented; empty by design.
-- TODO(SCENARIO-003): seed data for the real steps - see plan/scenarios.md (SCENARIO-003).
