# LICENSEURI https://yuruna.link/license
# Copyright (c) 2019-2026 by Alisson Sol et al.
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "amisad-common",
    srcs = ["src/lib.rs", "src/i18n.rs"],
    compile_data = glob(["locales/*.json"]),
    crate_name = "amisad_common",
    edition = "2021",
    visibility = ["//visibility:public"],
)

exports_files(["Cargo.toml", "src/database.rs"])
